baseurl = ""
title = "RoboTamer"
MetaDataFormat = "toml"
pygmentsuseclasses = false
DefaultContentLanguage = "en"
copyright = "© 2014 RoboTamer"
uglyurls = true


[indexes]
  tag = "tags"
  group = "groups"

[languages]
  [languages.en]
    languageName = "English"
    title = "RoboTamer"
    weight = 1

  [languages.tr]
    languageName = "Türkçe"
    title = "RoboTamer"
    weight = 2


[[menu.linux]]
    name = "bash"
    url = "/code/linux"
    weight = -200


[[menu.main]]
    name = "About"
    url = "/en/about"
    weight = -200

[[menu.main]]
    name = "PHP"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/en/groups/php/"
    weight = -170

[[menu.main]]
    name = "Go"
    url = "/en/groups/go/"
    weight = -180


