baseurl = ""
theme = "mainroad"
title = "RoboTamer"
MetaDataFormat = "toml"
pygmentsuseclasses = false
defaultContentLanguage = 'en'
copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
baseURL = '/'
uglyurls = true
canonifyURLs = true
paginate = "10" # Number of posts per page

[taxonomies]
  tag = 'tags'
  serie = 'series'
  categories = 'categories'
  group = 'groups'
  post = 'posts'
  page = 'pages'
  blog = 'blog'

[Author] # Used in authorbox
  name = "TaMeR"
  bio = 'Sailor, Blogger, and Coder'
  avatar = "img/robotamer.gif"

[Params]
mathjax = false # Enable MathJax

[Params.logo]
  image = "img/robotamer.gif" # Logo image. Path relative to "static"
  title = "RoboTamer" # Logo title, otherwise will use site title
  subtitle = "My little space on the net"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages

  # Enable widgets in given order
  widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
  # Enable parts of social widget
  telegram = 'robotamer'
  github = 'robotamer'
  gitlab = 'robotamer'
  bitbucket = 'robotamer'
  mastodon = 'https://mastodon.social/@robotamer'

[[Params.widgets.social.custom]]
  title = 'Mastodon'
  url = 'https://mastodon.social/@robotamer'
  #icon = 'mastodon.svg'

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 10
  [languages.tr]
    contentDir = 'content/tr'
    languageName = 'Türkçe'
    weight = 20

[menu]
[[menu.main]]
  identifier = 'blog'
  name = 'Blog'
  title = 'blog section'
  url = '/blog.html'
  weight = -210
  
[[menu.main]]
	identifier = 'about'
    name = 'About'
    url = '/about.html'
    weight = -200

[[menu.main]]
	identifier = 'contact'
    name = 'Contact'
    url = '/contact.html'
    weight = -190

[[menu.main]]
	identifier = 'linux'
    name = "Linux"
    pre = "<i class='fa fa-cubes'></i>"
    url = '/linux.html'
    weight = -160


[[menu.main]]
	identifier = 'php'
    name = "PHP"
    pre = "<i class='fa fa-cubes'></i>"
    url = '/code/php.html'
    weight = -170

[[menu.main]]
	identifier = 'go'
    name = "Go"
    url = '/code/go.html'
    weight = -180


[[menu.linux]]
    name = "bash"
    url = '/code/linux.html'
    weight = -200


